name: Load Object to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Sync to s3 bucket
      run: |
        cd 2119_gymso_fitness/
        aws s3 sync . s3://${{ secrets.AWS_S3_BUCKET }}/ --delete